# Generated by Django 3.2.7 on 2021-11-06 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0008_alter_announcement_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='src_ID',
        ),
    ]
