# Generated by Django 3.2.7 on 2021-12-10 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('announcements', '0009_remove_announcement_src_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='date',
            new_name='published',
        ),
    ]
