# Generated by Django 3.2.7 on 2021-11-21 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Officers',
            new_name='Officer',
        ),
    ]
