# Generated by Django 3.2.7 on 2021-11-21 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_rename_officers_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='generalinformation',
            name='name_acronym',
            field=models.CharField(default='BulSU-OSOA', max_length=100),
        ),
    ]
