# Generated by Django 3.2.7 on 2021-11-21 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_generalinformation_name_acronym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generalinformation',
            name='logo',
            field=models.ImageField(default='imageresources/osologo.svg', upload_to='imageresources/'),
        ),
        migrations.AlterField(
            model_name='officer',
            name='image',
            field=models.ImageField(default='imageresources/osologo.svg', upload_to='exectiveboard/'),
        ),
    ]
