# Generated by Django 3.2.7 on 2021-11-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0004_auto_20211121_1400'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypesOfOrganization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(default='Describe Type of Org')),
            ],
            options={
                'verbose_name_plural': 'Org Types',
            },
        ),
        migrations.AlterModelOptions(
            name='generalinformation',
            options={'verbose_name_plural': 'General Information'},
        ),
    ]
