# Generated by Django 3.2.7 on 2021-11-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_auto_20211121_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='image',
            field=models.ImageField(default='imageresources/osologo.svg', upload_to='executiveboard/'),
        ),
    ]
