# Generated by Django 3.2.7 on 2021-12-10 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_officer_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='hierarchy',
            field=models.IntegerField(choices=[(0, 'Head'), (1, 'Internal/Primary')], default=0, max_length=2),
        ),
    ]
