# Generated by Django 3.2.7 on 2021-12-10 07:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_officer_hierarchy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='hierarchy',
            field=models.PositiveIntegerField(choices=[(0, 'Head'), (1, 'Internal/Primary'), (2, 'External/Secondary'), (3, 'Others')], default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)]),
        ),
    ]
