# Generated by Django 3.2.7 on 2021-10-16 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ID', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('title', models.CharField(max_length=100)),
                ('event_stat_ID', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('description', models.TextField(blank=True)),
                ('icon', models.TextField()),
                ('img_ID', models.DecimalField(decimal_places=0, max_digits=1000)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
