# Generated by Django 3.2.7 on 2021-10-16 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211016_1355'),
        ('events', '0002_auto_20211016_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='img_ID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='images.imagecollection'),
        ),
    ]
