# Generated by Django 3.2.7 on 2021-10-16 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_auto_20211016_1355'),
        ('events', '0003_alter_event_img_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='icon',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='img_ID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='images.imagecollection'),
        ),
    ]
