# Generated by Django 3.2.7 on 2021-10-16 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('type', models.TextField()),
                ('program', models.TextField()),
                ('num_members', models.TextField()),
                ('category', models.TextField()),
                ('year_established', models.TextField()),
                ('by_lawssrc', models.TextField()),
                ('logo', models.TextField()),
                ('last_modified', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
    ]
