# Generated by Django 3.2.7 on 2021-10-16 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='type',
        ),
        migrations.AlterField(
            model_name='organization',
            name='by_lawssrc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.CharField(default='Student Organization', max_length=50),
        ),
        migrations.AlterField(
            model_name='organization',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='organization',
            name='num_members',
            field=models.TextField(max_length=150),
        ),
        migrations.AlterField(
            model_name='organization',
            name='program',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='organization',
            name='year_established',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
    ]
