# Generated by Django 3.2.7 on 2021-10-16 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_auto_20211016_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='num_members',
            field=models.DecimalField(decimal_places=0, max_digits=100),
        ),
    ]
