# Generated by Django 3.2.7 on 2021-10-16 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_num_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='by_lawssrc',
            new_name='by_laws_src',
        ),
        migrations.RenameField(
            model_name='organization',
            old_name='num_members',
            new_name='num_of_members',
        ),
    ]
