# Generated by Django 3.2.7 on 2021-11-26 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_auto_20211107_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='uploaded',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='by_laws_src',
            field=models.FileField(default='', upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='logo',
            field=models.ImageField(default='/imageresources/osologo.svg', upload_to='imageresources/'),
        ),
    ]
