# Generated by Django 3.2.7 on 2021-11-26 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_officer_image'),
        ('organization', '0013_auto_20211126_1250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(choices=[('o', 'OSOA'), ('n', 'none')], default='OSOA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.typesoforganization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(choices=[('o', 'OSOA'), ('r', 'Registered'), ('p', 'Pending')], max_length=20),
        ),
    ]
