# Generated by Django 3.2.7 on 2021-11-28 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_alter_officer_image'),
        ('organization', '0014_auto_20211126_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(default='OSOA', null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.typesoforganization'),
        ),
    ]
