# Generated by Django 3.2.7 on 2021-12-23 23:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_alter_officer_hierarchy'),
        ('organization', '0015_alter_organization_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='information.typesoforganization'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='num_of_members',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=100, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='organization',
            name='state',
            field=models.CharField(choices=[('o', 'OSOA'), ('r', 'Registered'), ('p', 'Pending'), ('s', 'Setup')], default='Setup', max_length=20),
        ),
        migrations.AlterField(
            model_name='organization',
            name='year_established',
            field=models.DecimalField(decimal_places=0, default=1990, max_digits=4, validators=[django.core.validators.MaxValueValidator(2050), django.core.validators.MinValueValidator(1990)]),
        ),
    ]
