# Generated by Django 3.2.7 on 2022-01-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_auto_20211224_0706'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='college_acronym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
