# Generated by Django 3.2.7 on 2021-11-28 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_organization_category'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Album',
            new_name='Albums',
        ),
        migrations.RenameModel(
            old_name='Image',
            new_name='Images',
        ),
    ]
