# Generated by Django 3.2.7 on 2021-11-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20211130_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='imgname',
        ),
        migrations.AddField(
            model_name='image',
            name='img_name',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
