# Generated by Django 3.2.7 on 2021-11-30 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20211130_1905'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img_name',
        ),
        migrations.AddField(
            model_name='image',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
