# Generated by Django 3.2.7 on 2021-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_auto_20211130_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
