# Generated by Django 3.2.7 on 2021-12-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0008_image_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='admin',
            field=models.BooleanField(),
        ),
    ]
