# Generated by Django 3.2.7 on 2021-12-10 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0009_alter_image_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='admin',
        ),
        migrations.AddField(
            model_name='album',
            name='admin',
            field=models.BooleanField(default=False),
        ),
    ]
