# Generated by Django 3.2.7 on 2021-10-17 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0009_documentcollection_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcollection',
            name='date_submitted',
        ),
    ]
