# Generated by Django 3.2.7 on 2021-10-17 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0010_remove_documentcollection_date_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollection',
            name='date_submitted',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
