# Generated by Django 3.2.7 on 2021-10-17 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0014_auto_20211017_2024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentcollection',
            name='submitted2',
        ),
    ]
