# Generated by Django 3.2.7 on 2021-10-28 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0015_remove_documentcollection_submitted2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='CLD',
            new_name='collection',
        ),
    ]
