# Generated by Django 3.2.7 on 2021-10-28 11:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0016_rename_cld_document_collection'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='docs/2021/10/28document_collections/<built-in function id>'),
            preserve_default=False,
        ),
    ]
