# Generated by Django 3.2.7 on 2021-12-28 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0019_auto_20211228_1233'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='documentcollection',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
