# Generated by Django 3.2.7 on 2021-12-28 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0021_auto_20211228_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
