# Generated by Django 3.2.7 on 2022-01-07 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_collection', '0023_documentcollection_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcollection',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
    ]
