# Generated by Django 3.2.7 on 2021-10-16 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20211016_1331'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageCollection',
        ),
        migrations.AlterModelOptions(
            name='imagecollection',
            options={'verbose_name_plural': 'Images'},
        ),
    ]
