# Generated by Django 2.0.7 on 2021-10-17 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_alter_imagecollection_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
