# Generated by Django 3.2.7 on 2021-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_auto_20211017_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
