# Generated by Django 3.2.7 on 2021-10-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_auto_20211028_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='img_src',
            field=models.ImageField(upload_to='imageresources/'),
        ),
    ]
