# Generated by Django 3.2.7 on 2021-10-16 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_auto_20211016_0924'),
    ]

    operations = [
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_begin', models.DateTimeField()),
                ('time_end', models.DateTimeField()),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('reminder_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.organization')),
            ],
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('order', models.DecimalField(decimal_places=0, max_digits=100)),
                ('color', models.CharField(max_length=11)),
                ('wp_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.workspace')),
            ],
        ),
        migrations.CreateModel(
            name='TaskState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.task', verbose_name='Task ID')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='tdl_ID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.todolist'),
        ),
        migrations.CreateModel(
            name='AssignedOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.officer', verbose_name='Officer ID')),
                ('TID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workspace.task', verbose_name='Task ID')),
            ],
        ),
    ]
