# Generated by Django 3.2.7 on 2021-10-16 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0004_taskstate_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='name',
            field=models.CharField(default='Organization Workspace', max_length=50),
        ),
    ]
