# Generated by Django 3.2.7 on 2021-12-13 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0012_auto_20211214_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='state',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='workspace.taskstate'),
        ),
    ]
